<?php

/**
 * An Inputfield for handling time inputs.
 */

class InputfieldTime extends Inputfield
{
    public static function getModuleInfo()
    {
        return array(
            'title'     => __('Inputfield Time', __FILE__),
            'summary'   => __('Allows entry of times in various formats', __FILE__),
            'version'   => 1,
            'permanent' => false,
            'autoload'  => false,
            'singular'  => false,
            'requires'  => array('FieldtypeTime'),
            'installs'  => array('FieldtypeTime'),
            'author'    => 'S. Dickinson, QBox.co',
        );
    }


    public function init()
    {
        $this->attr('type', 'text');
        $this->attr('size', 10);
        $this->attr('maxlength', 10);
        $this->attr('placeholder', '');
        $this->attr('pattern', '');
        parent::init();
    }


    public function ___renderValue()
    {
        return htmlspecialchars($this->value, ENT_QUOTES, "UTF-8");
    }


    public function ___render()
    {
        $out = "\n<input " . $this->getAttributesString() . " />";
        return $out;
    }



    public function getAttributes()
    {
        $attrs = parent::getAttributes();

        if (empty($attrs['size'])) {
            unset($attrs['size']);
            $attrs['class'] = (empty($attrs['class']) ? '' : $attrs['class'] . ' ') . 'InputfieldMaxWidth';
        }

        return $attrs;
    }



    public function setAttribute($key, $value)
    {
        if ($key == 'value') {
            $value = $this->sanitizeValue($value);
        }

        return parent::setAttribute($key, $value);
    }



    protected function sanitizeValue($value)
    {
        $value    = trim($value);
        $format   = $this->format;
        $colons   = $this->useColons;

        if (!strlen("$value")) {
            $value = '00:00:00';
        }

        $negative = substr($value, 0, 1) === '-';
        if($negative) {
            $value = substr($value, 1);
        }

        $neg_ok = '-' === substr($format, -1);
        if (!$neg_ok) {
            $negative = false;
        } else {
            $format = substr($format, 0, -1);
        }

        $value = str_replace('-', ':', $value);
        $value = preg_replace('/[^\d:]/', '', $value);

        if ($negative) {
            $value = '-' . $value;
        }

        return $value;
    }



    public function ___processInput(WireInputData $input)
    {
        parent::___processInput($input);

        $value = (string) $this->attr('value');
        if (strlen($value)) {
            /**
             * General time string regex - only allows '-', ':' or digits.
             */
            $regex = '#^[\d:-]+$#';
            if (!preg_match($regex, $value)) {
                $this->error($this->_('Only digits and colons (with or without a leading -) are allowed.'));
            }
        }

        return $this;
    }

}
